// Mocks generated by Mockito 5.4.6 from annotations
// in nexo/test/widget/tela_curso_player_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:nexo/models/models.dart' as _i3;
import 'package:nexo/services/chat_service.dart' as _i10;
import 'package:nexo/services/firestore_service.dart' as _i4;
import 'package:nexo/services/profile_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDocumentReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatRoom_1 extends _i1.SmartFake implements _i3.ChatRoom {
  _FakeChatRoom_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i4.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setFirestoreForTests(_i2.FirebaseFirestore? firestore) =>
      super.noSuchMethod(
        Invocation.method(
          #setFirestoreForTests,
          [firestore],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> createDeckFromPost(
    _i3.Post? post,
    List<Map<String, String>>? cardsData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDeckFromPost,
          [
            post,
            cardsData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addBaralho(
    _i3.Baralho? baralho,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBaralho,
          [
            baralho,
            userId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<List<_i3.Baralho>> getBaralhos(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBaralhos,
          [userId],
        ),
        returnValue: _i5.Stream<List<_i3.Baralho>>.empty(),
      ) as _i5.Stream<List<_i3.Baralho>>);

  @override
  _i5.Future<void> updateBaralho(
    String? userId,
    String? baralhoId,
    String? novoNome,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBaralho,
          [
            userId,
            baralhoId,
            novoNome,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteBaralho(
    String? userId,
    String? baralhoId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBaralho,
          [
            userId,
            baralhoId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addCard(
    _i3.Cartao? card,
    String? userId,
    String? baralhoId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCard,
          [
            card,
            userId,
            baralhoId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<List<_i3.Cartao>> getCards(
    String? userId,
    String? baralhoId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCards,
          [
            userId,
            baralhoId,
          ],
        ),
        returnValue: _i5.Stream<List<_i3.Cartao>>.empty(),
      ) as _i5.Stream<List<_i3.Cartao>>);

  @override
  _i5.Future<void> updateCard(
    String? userId,
    String? baralhoId,
    _i3.Cartao? card,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCard,
          [
            userId,
            baralhoId,
            card,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> copySharedDeck({
    required _i3.Baralho? sharedDeck,
    required String? hubId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copySharedDeck,
          [],
          {
            #sharedDeck: sharedDeck,
            #hubId: hubId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addVideo(_i3.VideoNexo? video) => (super.noSuchMethod(
        Invocation.method(
          #addVideo,
          [video],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<List<_i3.VideoNexo>> streamVideos(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamVideos,
          [userId],
        ),
        returnValue: _i5.Stream<List<_i3.VideoNexo>>.empty(),
      ) as _i5.Stream<List<_i3.VideoNexo>>);

  @override
  _i5.Future<void> updateVideo(_i3.VideoNexo? video) => (super.noSuchMethod(
        Invocation.method(
          #updateVideo,
          [video],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteVideo(
    String? userId,
    String? videoId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVideo,
          [
            userId,
            videoId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.DocumentReference<_i3.Curso>> createCurso(_i3.Curso? curso) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCurso,
          [curso],
        ),
        returnValue: _i5.Future<_i2.DocumentReference<_i3.Curso>>.value(
            _FakeDocumentReference_0<_i3.Curso>(
          this,
          Invocation.method(
            #createCurso,
            [curso],
          ),
        )),
      ) as _i5.Future<_i2.DocumentReference<_i3.Curso>>);

  @override
  _i5.Stream<List<_i3.Curso>> streamCursos(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamCursos,
          [userId],
        ),
        returnValue: _i5.Stream<List<_i3.Curso>>.empty(),
      ) as _i5.Stream<List<_i3.Curso>>);

  @override
  _i5.Stream<_i2.DocumentSnapshot<_i3.Curso>> getCursoStream(
    String? userId,
    String? cursoId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCursoStream,
          [
            userId,
            cursoId,
          ],
        ),
        returnValue: _i5.Stream<_i2.DocumentSnapshot<_i3.Curso>>.empty(),
      ) as _i5.Stream<_i2.DocumentSnapshot<_i3.Curso>>);

  @override
  _i5.Future<void> updateCurso(
    String? userId,
    _i3.Curso? curso,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCurso,
          [
            userId,
            curso,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteCurso(
    String? userId,
    String? cursoId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCurso,
          [
            userId,
            cursoId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> rateCurso(
    String? ownerId,
    String? cursoId,
    String? raterUserId,
    int? rating,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rateCurso,
          [
            ownerId,
            cursoId,
            raterUserId,
            rating,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<List<_i3.Lesson>> streamLessons(
    String? userId,
    String? cursoId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamLessons,
          [
            userId,
            cursoId,
          ],
        ),
        returnValue: _i5.Stream<List<_i3.Lesson>>.empty(),
      ) as _i5.Stream<List<_i3.Lesson>>);

  @override
  _i5.Future<void> addLesson(
    String? userId,
    String? cursoId,
    _i3.Lesson? lesson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLesson,
          [
            userId,
            cursoId,
            lesson,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateLesson(
    String? userId,
    String? cursoId,
    _i3.Lesson? lesson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLesson,
          [
            userId,
            cursoId,
            lesson,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteLesson(
    String? userId,
    String? cursoId,
    String? lessonId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLesson,
          [
            userId,
            cursoId,
            lessonId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateLessonOrder(
    String? userId,
    String? cursoId,
    List<_i3.Lesson>? lessons,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLessonOrder,
          [
            userId,
            cursoId,
            lessons,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<List<_i3.LessonComment>> streamLessonComments(
    String? userId,
    String? cursoId,
    String? lessonId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamLessonComments,
          [
            userId,
            cursoId,
            lessonId,
          ],
        ),
        returnValue: _i5.Stream<List<_i3.LessonComment>>.empty(),
      ) as _i5.Stream<List<_i3.LessonComment>>);

  @override
  _i5.Future<void> addLessonComment(
    String? userId,
    String? cursoId,
    String? lessonId,
    _i3.LessonComment? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLessonComment,
          [
            userId,
            cursoId,
            lessonId,
            comment,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileService extends _i1.Mock implements _i6.ProfileService {
  MockProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setFirestoreForTests(_i2.FirebaseFirestore? firestore) =>
      super.noSuchMethod(
        Invocation.method(
          #setFirestoreForTests,
          [firestore],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAuthForTests(_i7.FirebaseAuth? auth) => super.noSuchMethod(
        Invocation.method(
          #setAuthForTests,
          [auth],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<_i3.ProfessorStats?> getProfessorStatsStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfessorStatsStream,
          [userId],
        ),
        returnValue: _i5.Stream<_i3.ProfessorStats?>.empty(),
      ) as _i5.Stream<_i3.ProfessorStats?>);

  @override
  _i5.Future<void> followUser(
    String? currentUserId,
    String? targetUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [
            currentUserId,
            targetUserId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unfollowUser(
    String? currentUserId,
    String? targetUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [
            currentUserId,
            targetUserId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<_i3.UserModel?> getUserProfileStream(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfileStream,
          [uid],
        ),
        returnValue: _i5.Stream<_i3.UserModel?>.empty(),
      ) as _i5.Stream<_i3.UserModel?>);

  @override
  _i5.Future<_i3.UserModel?> getUserProfile(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [uid],
        ),
        returnValue: _i5.Future<_i3.UserModel?>.value(),
      ) as _i5.Future<_i3.UserModel?>);

  @override
  _i5.Future<void> createUserProfile({
    required String? uid,
    required String? username,
    required String? email,
    required String? bio,
    required List<String>? interests,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserProfile,
          [],
          {
            #uid: uid,
            #username: username,
            #email: email,
            #bio: bio,
            #interests: interests,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateUserProfile(
    String? uid,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [
            uid,
            data,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.UserModel>> getUsersFromIdList(List<String>? userIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsersFromIdList,
          [userIds],
        ),
        returnValue: _i5.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
      ) as _i5.Future<List<_i3.UserModel>>);

  @override
  _i5.Future<List<_i3.UserModel>> searchUsersByUsername({
    required String? query,
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsersByUsername,
          [],
          {
            #query: query,
            #currentUserId: currentUserId,
          },
        ),
        returnValue: _i5.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
      ) as _i5.Future<List<_i3.UserModel>>);

  @override
  _i5.Future<bool> isUsernameUnique(String? username) => (super.noSuchMethod(
        Invocation.method(
          #isUsernameUnique,
          [username],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String> uploadProfilePicture({
    required String? uid,
    required _i8.Uint8List? imageData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfilePicture,
          [],
          {
            #uid: uid,
            #imageData: imageData,
          },
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #uploadProfilePicture,
            [],
            {
              #uid: uid,
              #imageData: imageData,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<_i3.UserModel>> getBlockedUsers(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBlockedUsers,
          [userId],
        ),
        returnValue: _i5.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
      ) as _i5.Future<List<_i3.UserModel>>);

  @override
  _i5.Future<void> blockUser(
    String? currentUserId,
    String? targetUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [
            currentUserId,
            targetUserId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unblockUser(
    String? currentUserId,
    String? targetUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [
            currentUserId,
            targetUserId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i10.ChatService {
  MockChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setFirestoreForTests(_i2.FirebaseFirestore? firestore) =>
      super.noSuchMethod(
        Invocation.method(
          #setFirestoreForTests,
          [firestore],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAuthForTests(_i7.FirebaseAuth? auth) => super.noSuchMethod(
        Invocation.method(
          #setAuthForTests,
          [auth],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<List<_i3.ChatRoom>> getChatRoomsStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatRoomsStream,
          [userId],
        ),
        returnValue: _i5.Stream<List<_i3.ChatRoom>>.empty(),
      ) as _i5.Stream<List<_i3.ChatRoom>>);

  @override
  _i5.Future<_i3.ChatRoom?> getChatRoomById(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatRoomById,
          [roomId],
        ),
        returnValue: _i5.Future<_i3.ChatRoom?>.value(),
      ) as _i5.Future<_i3.ChatRoom?>);

  @override
  _i5.Stream<List<_i3.ChatMessage>> getMessagesStream(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesStream,
          [roomId],
        ),
        returnValue: _i5.Stream<List<_i3.ChatMessage>>.empty(),
      ) as _i5.Stream<List<_i3.ChatMessage>>);

  @override
  _i5.Future<void> sendMessage({
    required String? roomId,
    required String? text,
    required String? senderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #roomId: roomId,
            #text: text,
            #senderId: senderId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ChatRoom> getOrCreateDmRoom(
    _i3.UserModel? currentUser,
    _i3.UserModel? otherUser,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateDmRoom,
          [
            currentUser,
            otherUser,
          ],
        ),
        returnValue: _i5.Future<_i3.ChatRoom>.value(_FakeChatRoom_1(
          this,
          Invocation.method(
            #getOrCreateDmRoom,
            [
              currentUser,
              otherUser,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ChatRoom>);

  @override
  _i5.Future<_i3.ChatRoom?> createChatRoom(_i3.ChatRoom? room) =>
      (super.noSuchMethod(
        Invocation.method(
          #createChatRoom,
          [room],
        ),
        returnValue: _i5.Future<_i3.ChatRoom?>.value(),
      ) as _i5.Future<_i3.ChatRoom?>);
}
